
name: Create a new release
on:
  workflow_dispatch:
    inputs:
      ref:
        description: Commit name to release (defaults to master)
        required: false
      args:
        description: Additional command line arguments
        required: false

jobs:
  release:
    name: Draft Release
    runs-on: ubuntu-latest
    env:
      DOTNET_CLI_TELEMETRY_OPTOUT: 1
    steps:
    - name: Checkout the repository