
name: Test build
on:
  workflow_dispatch:
    inputs:
      ref:
        description: Commit name (defaults to master)
        required: false
      target:
        description: Command line
        required: true
        default: ResolveVersion --verbose

jobs:
  release:
    name: Test build
    runs-on: ubuntu-latest
    env:
      DOTNET_CLI_TELEMETRY_OPTOUT: 1
    steps:
    - name: Checkout the repository
      uses: actions/checkout@v2